services:
  db:
    build:
      context: ./container
      dockerfile: Dockerfile
    image: com.example.k83/test-sample-db:0.1.0
    container_name: db
    tmpfs:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - test-nw
networks:
  test-nw: