services:
  app:
    image: com.example.k83/test-sample-app:${APP_VER}
    container_name: app
    depends_on:
      - app-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - test-nw

  app-db:
    image: com.example.k83/test-sample-db:${APP_DB_VER}
    container_name: app-db
    volumes:
      - "test-sample-db-data:/var/lib/postgresql"
    environment:
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_NAME}
    networks:
      - test-nw

volumes:
  test-sample-db-data:

networks:
  test-nw: