services:
  app-test:
    image: com.example.k83/test-sample-app:0.1.0
    container_name: app-test
    depends_on:
      - app-test-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test
    networks:
      - test-nw

  app-test-db:
    build:
      context: ./container
      dockerfile: Dockerfile
    image: com.example.k83/test-sample-db:0.1.0
    container_name: app-test-db
    tmpfs:
      - /var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - test-nw

networks:
  test-nw: