spring:
  application:
    name: test-sample
  flyway:
    user:
      enabled: true
      locations: classpath:/user/migration
      baseline-on-migrate: true
      validate-on-migrate: true
      out-of-order: false
      table: flyway_schema_history
    product:
      enabled: true
      locations: classpath:/product/migration
      baseline-on-migrate: true
      validate-on-migrate: true
      out-of-order: false
      table: flyway_schema_history

mybatis:
  mapper-locations: classpath:/mapper/*.xml

