spring:
  datasource:
    user:
      jdbcUrl: jdbc:postgresql://app-test-db:5432/users
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
    product:
      jdbcUrl: jdbc:postgresql://app-test-db:5432/product
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver